#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PATH=$PATH:~/.local/bin
GAMECLIENT='gameclient'
export PATH
export GAMECLIENT

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '